version: '3.8'

volumes:
  wordpress_vol:
  mysql_vol:

networks:
  wordpress_net:
    driver: bridge

services:
  worpress:
    image: wordpress:6.2.0-php8.2-apache
    depends_on:
      - mysqldb
    networks:
      - wordpress_net
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysqldb:3306
      WORDPRESS_DB_USER: devpro
      WORDPRESS_DB_PASSWORD: devpro123
      WORDPRESS_DB_NAME: sitebd
    volumes:
      - wordpress_vol:/var/www/html

  mysqldb:
    image: mysql:8.0.33
    networks:
      - wordpress_net
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sitebd
      MYSQL_USER: devpro
      MYSQL_PASSWORD: devpro123
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mysql_vol:/var/lib/mysql