version: '3.8'

volumes:
  mariadb_vol:

networks:
  phpadmin_net:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.7
    networks:
      - phpadmin_net
    volumes:
      - mariadb_vol:/data/db
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_ROOT_HOST:
      MARIADB_USER: devopsuser
      MARIADB_PASSWORD: pro123456
      
  phpmyadmin:
    image: phpmyadmin:5.2.1
    networks:
      - phpadmin_net
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
